name: "CI"

on:
  push:
    branches:
      - "master"

jobs:
  ci:
    name: "CI"
    runs-on: ubuntu-latest
    steps:
      - name: "Success"
        run: "exit 0"

      - name: "Fail"
        run: "exit 1"

      - name: "This won't run"
        run: "echo heloo"
